# Generated by Django 2.1.5 on 2019-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_hash',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
